import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/providers";
import { useFullscreenContext } from "@/components/providers/fullscreen-provider";
import { cn } from "@/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isFullscreen } = useFullscreenContext();

  return (
    <html lang="en">
      <body
        className={cn(inter.className, isFullscreen ? "overflow-hidden" : "")}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
